version: "3.8"

services:

  redis:
    container_name: twitter_redis_container
    image: redis:6.2-rc-alpine
    ports:
      - "6379:6379"

  postgres:
    container_name: twitter_postgres_container
    image: postgres:14
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - ./typeorm/sql/create-uuid-ossp-extension.sql:/docker-entrypoint-initdb.d/uuid-init.sql
